export enum NETWORKS {
  DEFAULT = 57073,
  INKMAINNET = 57073,
  SONEIUMMAINNET = 1868,
  ABSTRACTMAINNET = 2741,
  BERA = 80094,
  UNICHAIN = 130,
  // COTI = 2632500,
  ZORA = 7777777,
  PLUMEMAINNET = 98865,
  APE = 33139,
  HEMI = 43111,
  CZ = 56,
  BASE = 8453,
  SONICMAINNET = 146,
  SCROLL = 534352,
  BLAST = 81457,
  TAIKO = 167000,
  POLY = 137,
  CREATOR_CHAIN = 66665,
  MONAD = 10143,
  // NEXUS = 393,
  // TABI_V2 = 9788,
  // ATHENE = 281123,
  // XRPL = 1449000,
  // SAHARA = 313313,
}

export const CHAIN_COLOR: { [key in NETWORKS]: string } = {
  [NETWORKS.INKMAINNET]: "#fff",
  [NETWORKS.SONEIUMMAINNET]: "#fff",
  [NETWORKS.ABSTRACTMAINNET]: "#fff",
  [NETWORKS.BERA]: "#FD7108",
  [NETWORKS.UNICHAIN]: "#fff",
  // [NETWORKS.COTI]: "#fff",
  [NETWORKS.ZORA]: "#72E1EA",
  [NETWORKS.PLUMEMAINNET]: "#f53a39",
  [NETWORKS.APE]: "#fff",
  [NETWORKS.HEMI]: "#fff",
  [NETWORKS.CZ]: "#f0b90b",
  [NETWORKS.BASE]: "#fff",
  [NETWORKS.SONICMAINNET]: "#fff",
  [NETWORKS.SCROLL]: "#FFDBB3",
  [NETWORKS.BLAST]: "#F4F53A",
  [NETWORKS.TAIKO]: "#E81899",
  [NETWORKS.POLY]: "#8247E5",
  [NETWORKS.CREATOR_CHAIN]: "#F4F53A",
  [NETWORKS.MONAD]: "#fff",
  // [NETWORKS.NEXUS]: "#fff",
  // [NETWORKS.TABI_V2]: "#FF8311",
  // [NETWORKS.ATHENE]: "#04D693",
  // [NETWORKS.XRPL]: "#FEFEFE",
  // [NETWORKS.SAHARA]: "#fff",
};

export const CHAIN_ICON: { [key in NETWORKS]: string } = {
  [NETWORKS.INKMAINNET]: "https://icons.llamao.fi/icons/chains/rsz_ink.jpg",
  [NETWORKS.SONEIUMMAINNET]:
    "https://icons.llamao.fi/icons/chains/rsz_soneium.jpg",
  [NETWORKS.ABSTRACTMAINNET]:
    "https://icons.llamao.fi/icons/chains/rsz_abstract.jpg",
  [NETWORKS.BERA]: "https://icons.llamao.fi/icons/chains/rsz_berachain.jpg",
  [NETWORKS.UNICHAIN]: "https://icons.llamao.fi/icons/chains/rsz_unichain.jpg",
  // [NETWORKS.COTI]: "",
  [NETWORKS.ZORA]: "https://icons.llamao.fi/icons/chains/rsz_zora.jpg",
  [NETWORKS.PLUMEMAINNET]: "https://chainlist.org/unknown-logo.png",
  [NETWORKS.APE]: "https://icons.llamao.fi/icons/chains/rsz_apechain.jpg",
  [NETWORKS.HEMI]: "https://icons.llamao.fi/icons/chains/rsz_hemi.jpg",
  [NETWORKS.CZ]: "https://icons.llamao.fi/icons/chains/rsz_binance.jpg",
  [NETWORKS.BASE]: "https://icons.llamao.fi/icons/chains/rsz_base.jpg",
  [NETWORKS.SONICMAINNET]: "https://icons.llamao.fi/icons/chains/rsz_sonic.jpg",
  [NETWORKS.SCROLL]: "https://icons.llamao.fi/icons/chains/rsz_scroll.jpg",
  [NETWORKS.BLAST]: "https://icons.llamao.fi/icons/chains/rsz_blast.jpg",
  [NETWORKS.TAIKO]: "https://icons.llamao.fi/icons/chains/rsz_taiko.jpg",
  [NETWORKS.POLY]: "https://icons.llamao.fi/icons/chains/rsz_polygon.jpg",
  [NETWORKS.CREATOR_CHAIN]: "https://chainlist.org/unknown-logo.png",
  [NETWORKS.MONAD]: "https://chainlist.org/unknown-logo.png",
  // [NETWORKS.NEXUS]: "",
  // [NETWORKS.TABI_V2]: "",
  // [NETWORKS.ATHENE]: "",
  // [NETWORKS.XRPL]: "",
  // [NETWORKS.SAHARA]: "",
};

export const getChainColor = (id: NETWORKS) => CHAIN_COLOR[id];
export const getChainIcon = (id: NETWORKS) => CHAIN_ICON[id];
