import { TLD } from "@/lib/model/domain";
import { NETWORKS } from "./chains";

export const tlds: TLD[] = [
  { chainId: NETWORKS.BERA, label: "honey", tld: "honey" },
  { chainId: NETWORKS.CZ, label: "cz", tld: "cz" },
  { chainId: NETWORKS.INKMAINNET, label: "ink", tld: "ink" },
  { chainId: NETWORKS.ZORA, label: "gold", tld: "gold" },
  { chainId: NETWORKS.BASE, label: "boss", tld: "boss" },
  { chainId: NETWORKS.SONICMAINNET, label: "speed", tld: "speed" },
  { chainId: NETWORKS.ABSTRACTMAINNET, label: "abs", tld: "abs" },
  { chainId: NETWORKS.SONEIUMMAINNET, label: "future", tld: "future" },
  { chainId: NETWORKS.PLUMEMAINNET, label: "goon", tld: "goon" },
  // { chainId: NETWORKS.FORM, label: "form", tld: "form" },
  { chainId: NETWORKS.SCROLL, label: "scroll", tld: "scroll" },
  { chainId: NETWORKS.BLAST, label: "blast", tld: "blast" },
  { chainId: NETWORKS.TAIKO, label: "🥁", tld: "%f0%9f%a5%81" },
  // { chainId: NETWORKS.MORPH, label: "koala", tld: "koala" },
  { chainId: NETWORKS.POLY, label: "poly", tld: "poly" },
  { chainId: NETWORKS.UNICHAIN, label: "defi", tld: "defi" },
  // { chainId: NETWORKS.COTI, label: "coti", tld: "coti" },
  { chainId: NETWORKS.APE, label: "ape", tld: "ape" },
  { chainId: NETWORKS.HEMI, label: "hvm", tld: "hvm" },
  // { chainId: NETWORKS.MINT, label: "nft", tld: "nft" },
  // { chainId: NETWORKS.XLAYER, label: "xlayer", tld: "xlayer" },
  { chainId: NETWORKS.CREATOR_CHAIN, label: "ceo", tld: "ceo" },
  { chainId: NETWORKS.MONAD, label: "mnd", tld: "mnd" },
  // { chainId: NETWORKS.NEXUS, label: "nexus", tld: "nexus" },
  // { chainId: NETWORKS.MEGA, label: "mega", tld: "mega" },
  // { chainId: NETWORKS.BARTIO, label: "honey", tld: "honey" },
  // { chainId: NETWORKS.TABI_V2, label: "tabi", tld: "tabi" },
  // { chainId: NETWORKS.STORY, label: "story", tld: "story" },
  // { chainId: NETWORKS.ATHENE, label: "athene", tld: "athene" },
  // { chainId: NETWORKS.XRP, label: "xrp", tld: "xrp" },
  // { chainId: NETWORKS.XRPL, label: "xrpl", tld: "xrpl" },
  // { chainId: NETWORKS.SAHARA, label: "sahara", tld: "sahara" },
  // { chainId: NETWORKS.BOBA, label: "boba", tld: "boba" },
  // { chainId: NETWORKS.ARTHERA, label: "arthera", tld: "arthera" },
  // { chainId: NETWORKS.NEOX, label: "neox", tld: "neox" },
  // { chainId: NETWORKS.TABI, label: "tabi_v1", tld: "tabi_v1" },
  // { chainId: NETWORKS.ZKCANDY, label: "candy",tld: "candy" },
  // { chainId: NETWORKS.ZKLINK, label: "zkl", tld: "zkl" },
  // { chainId: NETWORKS.ZIRCUIT, label: "zrc", tld: "zrc" },
  // { chainId: NETWORKS.FIRE, label: "5ire",tld: "5ire" },
];
